# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         RDF-Helper
version:      1.03
version_from: lib/RDF/Helper.pm
installdirs:  site
requires:
    Data::Uniqid:                  0
    Math::BigInt:                  0
    RDF::Query:                    1.040
    URI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
